// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Script, console} from "forge-std/Script.sol";
import {DemoToken} from "../src/DemoToken.sol";
import {ProfitMachine} from "../src/ProfitMachine.sol";
import {LossMachine} from "../src/LossMachine.sol";
import {YieldFarm} from "../src/YieldFarm.sol";
import {TaxVerifier} from "../src/TaxVerifier.sol";

contract DeployScript is Script {
    // Real SP1 Groth16 Verifier Gateway on Sepolia
    // From: https://docs.succinct.xyz/docs/sp1/verification/contract-addresses
    address constant SP1_VERIFIER_SEPOLIA = 0x397A5f7f3dBd538f23DE225B51f532c34448dA9B;

    // Real VK hash for tax-zk program (generated by SP1 prover setup)
    // Updated after Section 87A rebate fix
    bytes32 constant TAX_ZK_VKEY = 0x00e443478c063561810f469214d4e6d80639bd6da21eab50470b7ca5a52c726c;

    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);

        // Deploy DemoToken
        DemoToken token = new DemoToken();
        console.log("DemoToken deployed at:", address(token));

        // Deploy ProfitMachine
        ProfitMachine profit = new ProfitMachine(address(token));
        console.log("ProfitMachine deployed at:", address(profit));

        // Deploy LossMachine
        LossMachine loss = new LossMachine(address(token));
        console.log("LossMachine deployed at:", address(loss));

        // Deploy YieldFarm
        YieldFarm farm = new YieldFarm(address(token));
        console.log("YieldFarm deployed at:", address(farm));

        // Deploy TaxVerifier with real SP1 verifier and real VK
        TaxVerifier taxVerifier = new TaxVerifier(SP1_VERIFIER_SEPOLIA, TAX_ZK_VKEY);
        console.log("TaxVerifier deployed at:", address(taxVerifier));

        vm.stopBroadcast();

        // Print summary
        console.log("\n=== Deployment Summary ===");
        console.log("DemoToken:        ", address(token));
        console.log("ProfitMachine:    ", address(profit));
        console.log("LossMachine:      ", address(loss));
        console.log("YieldFarm:        ", address(farm));
        console.log("SP1 Verifier:     ", SP1_VERIFIER_SEPOLIA);
        console.log("Tax ZK VKey:      ");
        console.logBytes32(TAX_ZK_VKEY);
        console.log("TaxVerifier:      ", address(taxVerifier));
    }
}
